EXTRA_CFLAGS += -Iarch/arm/mach-msm -Iarch/arm/tools

obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7x27a_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7x27a-regulator_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7627a-bt_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7627a-camera_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7627a-display_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7627a-io_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7627a-storage_l4ii_cdma.o
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7627a-wlan_l4ii_cdma.o

obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += board-msm7x27a-sound_l4ii_cdma.o
ifndef CONFIG_LGE_SWITCH_GPIO
obj-$(CONFIG_MACH_MSM7X27A_L4II_CDMA) += lge_gpio_h2w_l4ii_cdma.o
endif
